// This file is generated by yarn build:icons

  export type IconName =
    | "arrow-bottom"
  | "arrow-long-right"
  | "bar"
  | "facebook"
  | "linkedin"
  | "moon"
  | "paper-plane"
  | "pinterest"
  | "play"
  | "quote-left"
  | "sun"
  | "twitter"